format = """
$directory\
$git_branch\
$git_status\
$python\
$golang\
$c\
$cpp\
$rust
$character
"""
add_newline = true
scan_timeout = 10


[line_break]
disabled = true

[fill]
symbol = " "

# 
[username]
show_always = true
format = '[ $user |]()'

[directory]
# style = "bg:#434C5E"
format = "[ $path|]($style)"
fish_style_pwd_dir_length=1
truncate_to_repo = true
# truncation_length = 3
# truncation_symbol = "…/"

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[✗](bold red)'

[python]
format = '$symbol[(\($virtualenv\))]($style)'
pyenv_version_name = true

[rust]
format = '[$symbol]($style)'

[c]
format = '[$symbol]($style)'

[cpp]
format = '[$symbol]($style)'

[golang]
symbol = " "
format = '[$symbol]($style)'

[aws]
disabled = true

[git_branch]
format = '[ $symbol$branch]($style)'

[git_status]
style="purple"
format = '[ $all_status$ahead_behind | ]($style)'

[git_metrics]
disabled = false

[cmd_duration]
min_time = 3_000
format = "[ $duration ]()"
style = "white"
